general:
  imagePullPolicy: Never  # Never will use images from local machine (docker local registry)
  imageTag: 1.0.0
  minimumStartupDelayInSecs: 5  # Minimum time any container will need to start up.
  startupProbePeriod: 3  # How oftern it will check if the container has finished its start up.
  startupFailureThreshold: 20  # Max number of time it will check if the container has finished its start up.
  livenessProbePeriod: 2
  livenessFailureThreshold: 2  # How often will check if the container is alive,
  readinessProbePeriod: 2
  readinessFailureThreshold: 2  # How often will check if the container can handle requests.
  preStopTimeInSec: 10  # PreStop gives time for the actual pod state to propagate and stop receiving requests.
  maxGracefulTimeInSecs: 72  # PreStop hook time + Spring grateful shutdown time + 2 secs (to allow Spring to finish).

currency:
  name: currency
  image: com.mecc/currency
  containerPort: 9004
  clusterPort: 9004
  replicas: 1
  requests:
    mem: 566Mi # Initial x 1.5
    cpu: 40m  # Initial x 4
  externalAccess:
    enabled: false
  activeProfiles:  # The active profiles should NOT be used to load properties for different environments: dev, prod, etc. Instead a new Helm release should be created with different values.
  nodeSel:

exchangeRate:
  name: exchange-rate
  image: com.mecc/exchange-rate
  containerPort: 9002
  clusterPort: 9002
  replicas: 1
  requests:
    mem: 538Mi # Initial x 1.5
    cpu: 24m  # Initial x 4
  externalAccess:
    enabled: false
  activeProfiles:  # The active profiles should NOT be used to load properties for different environments: dev, prod, etc. Instead a new Helm release should be created with different values.
  nodeSel:

simpleRest:
  name: simple-rest
  image: com.mecc/simple-rest
  containerPort: 9003
  clusterPort: 9003
  replicas: 1
  requests:
    mem: 580Mi # Initial x 1.5
    cpu: 32m  # Initial x 4
  externalAccess:
    enabled: true
    port: 30890  # Typically in the range 30000-32768
  secrets:
    secretMsg: "U2VjcmV0IG1lc3NhZ2UgY29tbWluZyBmcm9tIEs4cwo="   # Must be Base64 encoded.
  activeProfiles:  # The active profiles should NOT be used to load properties for different environments: dev, prod, etc. Instead a new Helm release should be created with different values. This is more to change the way the app should behave (if needed).
  nodeSel:

