general:
  imagePullPolicy: Never  # Never will use images from local machine (docker local registry)
  imageTag: 1.0.0

configServer:
  name: config-server
  image: com.mecc/config-server
  containerPort: 8888
  clusterPort: 8888
  replicas: 1
  externalAccess:
    enabled: true
    port: 30888  # Typically in the range 30000-32768
  nodeSel:

serviceDiscovery:
  name: service-discovery
  image: com.mecc/service-discovery-agent
  containerPort: 8889
  clusterPort: 8889
  replicas: 1
  externalAccess:
    enabled: true
    port: 30889  # Typically in the range 30000-32768
  nodeSel:

simpleRest:
  name: simple-rest
  image: com.mecc/simple-rest
  containerPort: 9003
  clusterPort: 9003
  replicas: 1
  externalAccess:
    enabled: true
    port: 30890  # Typically in the range 30000-32768
  nodeSel:

currency:
  name: currency
  image: com.mecc/currency
  containerPort: 9004
  clusterPort: 9004
  replicas: 1
  externalAccess:
    enabled: false
  nodeSel:

exchangeRate:
  name: exchange-rate
  image: com.mecc/exchange-rate
  containerPort: 9002
  clusterPort: 9002
  replicas: 1
  externalAccess:
    enabled: false
  nodeSel:

