services:
  config-server:
    image: com.mecc/config-server:1.0.0
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: mecckey
    volumes:
      - /Users/manuelcalvo/Documents/aprojects/SpringProjects/SpringCloudLearning/config-server/src/main/resources/configs:/opt/mecc/configs
    healthcheck:
      test: curl --fail http://localhost:8888/actuator/ || exit 1
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 10s
    networks:
      - mecc

  service-discovery-agent-1:
    image: com.mecc/service-discovery-agent:1.0.0
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "8889:8889"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_HOST: service-discovery-agent-1
      DISCOVERY_SERVICE_ZONE: default
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8889/actuator/ || exit 1
      interval: 5s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - mecc

  service-discovery-agent-2:
    image: com.mecc/service-discovery-agent:1.0.0
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "8890:8889"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/
      DISCOVERY_SERVICE_HOST: service-discovery-agent-2
      DISCOVERY_SERVICE_ZONE: default
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8889/actuator/ || exit 1
      interval: 5s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - mecc

  exchange-rate:
    image: com.mecc/exchange-rate:1.0.0
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "9002:9002"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/, http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_ZONE: default
    depends_on:
      config-server:
        condition: service_healthy
      service-discovery-agent-1:
        condition: service_healthy
      service-discovery-agent-2:
        condition: service_healthy
    healthcheck:
      test: grpc_health_probe -addr=localhost:9002 || exit 1
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 10s
    networks:
      - mecc

  currency1:
    image: com.mecc/currency:1.0.0
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "9004:9004"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/, http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_ZONE: default
    depends_on:
      config-server:
        condition: service_healthy
      service-discovery-agent-1:
        condition: service_healthy
      service-discovery-agent-2:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:9004/actuator/ || exit 1
      interval: 5s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - mecc

  currency2:
    image: com.mecc/currency:1.0.0
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "9005:9004"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/, http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_ZONE: default
    depends_on:
      config-server:
        condition: service_healthy
      service-discovery-agent-1:
        condition: service_healthy
      service-discovery-agent-2:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:9004/actuator/ || exit 1
      interval: 5s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - mecc

  simple-rest:
    image: com.mecc/simple-rest:1.0.0
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "9003:9003"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/, http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_ZONE: default
      EXCHANGE_RATE_SERVICE_NAME: exchange-rate
      CURRENCY_SERVICE_NAME: currency
    depends_on:
      config-server:
        condition: service_healthy
      service-discovery-agent-1:
        condition: service_healthy
      service-discovery-agent-2:
        condition: service_healthy
      exchange-rate:
        condition: service_healthy
      currency1:
        condition: service_healthy
      currency2:
        condition: service_healthy
    networks:
      - mecc

networks:
  mecc: