services:
  config-server:
    image: com.mecc/config-server:1.0.0
    deploy:
      resources:
        limits:
          memory: 768M
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: mecckey
    volumes:
      - /Users/manuelcalvo/Documents/aprojects/SpringProjects/SpringCloudLearning/config-server/src/main/resources/configs:/opt/mecc/configs
    networks:
      - mecc

  service-discovery-agent-1:
    image: com.mecc/service-discovery-agent:1.0.0
    deploy:
      resources:
        limits:
          memory: 768M
    ports:
      - "8889:8889"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_HOST: service-discovery-agent-1
      DISCOVERY_SERVICE_ZONE: default
    networks:
      - mecc

  service-discovery-agent-2:
    image: com.mecc/service-discovery-agent:1.0.0
    deploy:
      resources:
        limits:
          memory: 768M
    ports:
      - "8890:8889"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/
      DISCOVERY_SERVICE_HOST: service-discovery-agent-2
      DISCOVERY_SERVICE_ZONE: default
    networks:
      - mecc

  exchange-rate:
    image: com.mecc/exchange-rate:1.0.0
    deploy:
      resources:
        limits:
          memory: 768M
    ports:
      - "9002:9002"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/, http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_ZONE: default
    networks:
      - mecc

  currency1:
    image: com.mecc/currency:1.0.0
    deploy:
      resources:
        limits:
          memory: 768M
    ports:
      - "9004:9004"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/, http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_ZONE: default
    networks:
      - mecc

  currency2:
    image: com.mecc/currency:1.0.0
    deploy:
      resources:
        limits:
          memory: 768M
    ports:
      - "9005:9004"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/, http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_ZONE: default
    networks:
      - mecc

  simple-rest:
    image: com.mecc/simple-rest:1.0.0
    deploy:
      resources:
        limits:
          memory: 768M
    ports:
      - "9003:9003"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_URL: http://config-server:8888
      DISCOVERY_SERVICES: http://service-discovery-agent-1:8889/eureka/, http://service-discovery-agent-2:8889/eureka/
      DISCOVERY_SERVICE_ZONE: default
      EXCHANGE_RATE_SERVICE_NAME: exchange-rate
      CURRENCY_SERVICE_NAME: currency
    networks:
      - mecc

networks:
  mecc: