---
openapi: 3.0.2
info:
  title: Currency
  version: 1.0.0
  description: "Built using: https://studio.apicur.io/"
paths:
  /currencies:
    get:
      tags:
      - currency
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
          description: There are some currencies.
        "204":
          description: There are no currencies.
      operationId: getCurrencies
components:
  schemas:
    Currency:
      description: ""
      required:
      - code
      - name
      type: object
      properties:
        code:
          description: ""
          type: string
        name:
          description: ""
          type: string
