info:
  app:
    name: Currency Microservice
    description: Currency Microservice

server:
  port: 9004
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  jmx:
    enabled: true  # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure.include: info, health
  endpoint:
    info.enabled: true
    health.enabled: true
    health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true