server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  jmx:
    enabled: true

  cloud:
    config:
      server:
        native:
          search-locations:
            - "file:./src/main/resources/configs/{application}"
            - "classpath:/configs/{application}"
            - "file:/opt/mecc/configs/{application}"

encrypt:
  key: mecckey

info:
  app:
    name: Cloud Configuration microservice
    description: Cloud Configuration application
    version: 1.0.0

management:
  info:
    env:
      enabled: true
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

