{{- $service := .Values.exchangeRate }}
{{- $image := printf "%s/%s:%s" .Values.general.imagePrefix $service.image .Values.general.imageTag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ $service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ $service.name }}
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ $service.name }}
    spec:
      affinity:
      {{- with $service.affinities }}
{{ . | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.general.maxGracefulTimeInSecs }}
      containers:
        - lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep {{ .Values.general.preStopTimeInSec }}" ]  # Prevent requests from being received while the container is terminated and the Pod status is propageted:  https://hackmd.io/@ryanjbaxter/spring-on-k8s-workshop#Graceful-Shutdown https://linkerd.io/2.12/tasks/graceful-shutdown/#graceful-shutdown-in-kubernetes
          startupProbe:
            grpc: # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe  https://github.com/yidongnan/grpc-spring-boot-starter/issues/123
              port: {{ $service.port }}
            initialDelaySeconds: {{ .Values.general.minimumStartupDelayInSecs }}
            periodSeconds: {{ .Values.general.startupProbePeriod }}
            failureThreshold: {{ .Values.general.startupFailureThreshold }}
          livenessProbe:
            grpc:
              port: {{ $service.port }}
            periodSeconds: {{ .Values.general.livenessProbePeriod }}
            failureThreshold: {{ .Values.general.livenessFailureThreshold }}
          readinessProbe:
            grpc:
              port: {{ $service.port }}
            periodSeconds: {{ .Values.general.readinessProbePeriod }}
            failureThreshold: {{ .Values.general.readinessFailureThreshold }}
          resources:
            requests:
              memory: {{ $service.requests.mem }}
              cpu: {{ $service.requests.cpu }}
          name: {{ $service.name }}
          image: {{ $image }}
          imagePullPolicy: {{ .Values.general.imagePullPolicy }}
          securityContext:  # https://elastisys.com/howto-stop-running-containers-as-root-in-kubernetes/
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            allowPrivilegeEscalation: false
          ports:
            - containerPort: {{ $service.port }}
          env:
            - name: K8S_CONFIG_ENABLED
              value: 'true'
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $service.activeProfiles }}
            - name: APP_CONFIG_MAP  # This can be used to override app properties from a ConfigMap https://docs.spring.io/spring-cloud-kubernetes/docs/2.1.5/reference/html/#configmap-propertysource
              value: "{{ .Release.Name }}-{{ $service.name }}"
            - name: JAVA_OPTS
              value: {{ $service.javaOpts }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ $service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ $service.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ $service.name }}
  ports:
    - protocol: TCP
      port: {{ $service.port }}  # By default, the targetPort is set to the same value as the port field
---
{{- if $service.externalAccess.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ $service.name }}-ext-access
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ $service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-{{ $service.name }}
  ports:
    - protocol: TCP
      port: {{ $service.port }}  # By default, the targetPort is set to the same value as the port field
      nodePort: {{ $service.externalAccess.port }}
---
{{- end }}